services:
    database:
      container_name: stockscrape_db
      image: postgres:17.2
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - "${DB_HOST}:${DB_PORT}:${DB_PORT}"
      restart: always
      volumes:
          - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local