_BALANCE_SHEET_MAPPINGS = {
    "Cash and Cash Equivalents":            "cash_and_cash_equivalents",
    "Short-Term Investments":               "short_term_investments",
    "Net Receivables":                      "net_receivables",
    "Inventory":                            "inventory",
    "Other Current Assets":                 "other_current_assets",
    "Total Current Assets":                 "total_current_assets",
    "Fixed Assets":                         "fixed_assets",
    "Goodwill":                             "goodwill",
    "Intangible Assets":                    "intangible_assets",
    "Other Assets":                         "other_assets",
    "Deferred Asset Charges":               "deferred_asset_charges",
    "Total Assets":                         "total_assets",
    "Accounts Payable":                     "accounts_payable",
    "Short-Term Debt":                      "short_term_debt",
    "Other Current Liabilities":            "other_current_liabilities",
    "Total Current Liabilities":            "total_current_liabilities",
    "Long-Term Debt":                       "long_term_debt",
    "Other Liabilities":                    "other_liabilities",
    "Deferred Liability Charges":           "deferred_liability_charges",
    "Misc. Stocks":                         "misc_stocks",
    "Minority Interest":                    "minority_interest",
    "Total Liabilities":                    "total_liabilities",
    "Common Stocks":                        "common_stocks",
    "Capital Surplus":                      "capital_surplus",
    "Treasury Stock":                       "treasury_stock",
    "Other Equity":                         "other_equity",
    "Total Equity":                         "total_equity",
    "Total Liabilities & Equity":           "total_liabilities_and_equity",
}
